# Generated by Django 5.1.6 on 2025-02-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
