# Generated by Django 5.1.6 on 2025-03-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_discussion_comment_liveclass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[("Beginner", "Beginner"), ("Professional", "Professional")],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[("First", "First"), ("Second", "Second")], max_length=200
            ),
        ),
    ]
