# Generated by Django 4.2.25 on 2025-11-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_geminiquizconfig_geminiquizsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="geminiquizconfig",
            name="questions_per_session",
            field=models.IntegerField(
                default=20, help_text="Number of questions to show per quiz session"
            ),
        ),
        migrations.AddField(
            model_name="geminiquizsession",
            name="session_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="geminiquizsession",
            name="session_questions",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
