# Generated by Django 4.2.25 on 2025-11-29 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0001_initial"),
        ("quiz", "0003_geminiquizconfig_questions_per_session_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeminiQuizConfig",
            new_name="GroqQuizConfig",
        ),
        migrations.RenameModel(
            old_name="GeminiQuizSession",
            new_name="GroqQuizSession",
        ),
    ]
