# Generated by Django 5.1.6 on 2025-02-25 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_notification_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="student",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.student",
            ),
        ),
    ]
