# Generated by Django 5.1.6 on 2025-03-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_notification_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
